# Generated by Django 4.0.4 on 2024-07-13 14:14

from django.db import migrations, models
import django.db.models.deletion
import wander_wave.models


class Migration(migrations.Migration):

    dependencies = [
        ('wander_wave', '0002_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photos',
        ),
        migrations.CreateModel(
            name='PostPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=wander_wave.models.post_photo_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_photos', to='wander_wave.post')),
            ],
        ),
    ]
