# Generated by Django 4.0.4 on 2024-06-26 12:31

from django.db import migrations, models
import wander_wave.models


class Migration(migrations.Migration):

    dependencies = [
        ('wander_wave', '0002_remove_post_photos_postfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to=wander_wave.models.post_photo_path),
        ),
        migrations.DeleteModel(
            name='PostFile',
        ),
    ]
