# Generated by Django 4.0.4 on 2024-07-19 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wander_wave', '0002_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='is_read',
            new_name='is_ready',
        ),
    ]
