# Generated by Django 4.0.4 on 2024-06-26 12:40

from django.db import migrations, models
import django.db.models.deletion
import wander_wave.models


class Migration(migrations.Migration):

    dependencies = [
        ('wander_wave', '0003_post_photos_delete_postfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photos',
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=wander_wave.models.post_photo_path)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='wander_wave.post')),
            ],
        ),
    ]
