# Generated by Django 4.0.4 on 2024-07-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wander_wave', '0003_remove_post_photos_postphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='postphoto',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='posts', to='wander_wave.postphoto'),
        ),
    ]
