# Generated by Django 4.0.4 on 2024-07-19 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wander_wave', '0003_rename_is_read_notification_is_ready'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='is_ready',
            new_name='is_read',
        ),
    ]
