# Generated by Django 4.0.4 on 2024-06-26 13:25

from django.db import migrations, models
import wander_wave.models


class Migration(migrations.Migration):

    dependencies = [
        ('wander_wave', '0006_files_remove_post_photos_post_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='files',
        ),
        migrations.AddField(
            model_name='post',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to=wander_wave.models.post_photo_path),
        ),
        migrations.DeleteModel(
            name='Files',
        ),
    ]
