# Generated by Django 4.0.4 on 2024-07-04 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wander_wave', '0008_remove_post_comments_comment_post'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
    ]
