version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/my_media:/files/media
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate && 
            python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db


  db:
    image: postgres:16.2-alpine3.19
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - my_db:$PGDATA


volumes:
  my_db:
  my_media:
