# Generated by Django 4.0.4 on 2024-08-23 13:25

import backend.wander_wave.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wander_wave', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photos',
        ),
        migrations.CreateModel(
            name='PostPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=backend.wander_wave.models.post_photo_path)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_photos', to='wander_wave.post')),
            ],
        ),
    ]
