# Generated by Django 4.0.4 on 2024-08-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wander_wave', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostPhoto',
            new_name='Photo',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='photo',
            new_name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='uploaded_photos',
            field=models.ManyToManyField(related_name='posts', to='wander_wave.photo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(related_name='posts', to='wander_wave.hashtag'),
        ),
    ]
