# Generated by Django 4.0.4 on 2024-08-13 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wander_wave', '0002_rename_postphoto_photo_rename_photo_photo_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uploaded_photos',
        ),
    ]
